TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
# DB += ipimb.db

#----------------------------------------------------
# Create and install (or just install)
# Autosave request files, templates, substitutions like this
# REQ += autosave_ipimb.req
#REQ += pcds_ad.tpl-req
#REQ += pcds_ad_stream.tpl-req
#REQ += pcds_ad_plugin_roi.tpl-req
#REQ += pcds_ad_plugin_stats.tpl-req

#----------------------------------------------------
# Create and install (or just install)
# Archive files, templates, substitutions like this
# ARCHIVE += archive_ipimb.archive
ARCHIVE += pcds_ad.tpl-arch
ARCHIVE += pcds_ad_stream.tpl-arch
ARCHIVE += pcds_ad_plugin_roi.tpl-arch
ARCHIVE += pcds_ad_plugin_stats.tpl-arch
ARCHIVE += pcds_ad_plugin_overlay.tpl-arch
ARCHIVE += pcds_ad_basler.tpl-arch

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

